### ISSUE TITLE
"import scrollphathd as sphd" error

### ISSUE THREAD

**Issue by dialektike** [pimoroni/scroll-phat-hd#46]
Hi! 

I was importing the scrollphathd library in Pi Zero W. 

l founding error this.

```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scrollphathd as sphd
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/scrollphathd/is31fl3731.py", line 11, in <module>
    import smbus
ImportError: No module named 'smbus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/scrollphathd/__init__.py", line 3, in <module>
    from . import is31fl3731
  File "/usr/local/lib/python3.5/dist-packages/scrollphathd/is31fl3731.py", line 13, in <module>
    if version_info[0] < 3:
NameError: name 'version_info' is not defined
```

**Comment by Gadgetoid** [comment]
If you installed the library from GitHub you'll need to `sudo apt install python3-smbus`.

We historically didn't include certain dependencies in our packages, since pip would fall over itself trying to satisfy them- often throwing a missing `python.h` error, or at best spending forever compiling the dependency- when it;s just much simpler to grab the binary packet from apt.

With Python wheels now a thing, it might be possible to change this.
